# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vcloud'

# ubuntu1204_box_url = "http://roecloudsrv001/vagrant/vcloud/ubuntu1204.box"
ubuntu1204_box_url = "http://roecloudsrv001/vagrant/vcloud/fake.box"

nodes = [
  { :hostname => "web-vm",  :box => "ubuntu1204", :box_url => ubuntu1204_box_url } ,
  { :hostname => "ssh-vm",  :box => "ubuntu1204", :box_url => ubuntu1204_box_url }
]

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vcloud")
    config.vm.provider :vcloud do |vcloud|
      vcloud.vapp_prefix = "ubuntu1204"
    end
  end

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.hostname = node[:hostname]
      node_config.vm.box_url = node[:box_url]
      node_config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
      node_config.vm.provision "shell", path: "scripts/provision.sh"
    end
  end
end

