# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu1204-desktop"

  config.vm.provision "shell", path: "scripts/install-git.sh"
  config.vm.provision "shell", path: "scripts/install-packer.sh"
  config.vm.provision "shell", path: "scripts/install-vagrant.sh"
  config.vm.provision "shell", path: "scripts/install-virtualbox.sh"

  config.vm.provider "vcloud" do |v|
    v.memory = 4096
    v.cpus = 2
    v.nested_hypervisor = true
  end
  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--vram", "32"]
  end

end
