# -*- mode: ruby -*-
# vi: set ft=ruby :

win2012r2_vm_box_url = "../../../packer-windows/windows_2012_r2_vmware.box"

nodes = [
  { :hostname => "dc",  :box => "windows_2012_r2", :box_url => win2012r2_vm_box_url }
]

Vagrant.configure("2") do |config|

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.hostname = node[:hostname]
      node_config.vm.box_url = node[:box_url]
      node_config.windows.set_work_network = true
      node_config.vm.guest = :windows 
      node_config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
      # node_config.vm.provision :puppet do |puppet|
      #   puppet.manifests_path = 'puppet/manifests'
      #   puppet.manifest_file = 'site.pp'
      #   puppet.module_path = 'puppet/modules'
      # end
    end
  end
end

